// <auto-generated />
using System;
using Homan.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Homan.DAL.Migrations
{
    [DbContext(typeof(HomanContext))]
    [Migration("20181121184031_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Homan.DAL.Entities.HomeSpace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("HomeSpaces");
                });

            modelBuilder.Entity("Homan.DAL.Entities.HomeSpaceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<Guid>("HomeSpaceListId");

                    b.Property<string>("Name");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("HomeSpaceListId");

                    b.HasIndex("UserId");

                    b.ToTable("HomeSpaceItems");
                });

            modelBuilder.Entity("Homan.DAL.Entities.HomeSpaceItemList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<Guid>("HomeSpaceId");

                    b.Property<string>("Name");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("HomeSpaceId");

                    b.HasIndex("UserId");

                    b.ToTable("HomeSpaceItemLists");
                });

            modelBuilder.Entity("Homan.DAL.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<string>("Email");

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail");

                    b.Property<string>("NormalizedUserName");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Homan.DAL.Entities.UserInHomeSpace", b =>
                {
                    b.Property<Guid>("HomeSpaceId");

                    b.Property<Guid>("UserId");

                    b.HasKey("HomeSpaceId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserInHomeSpaces");
                });

            modelBuilder.Entity("Homan.DAL.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<string>("Name");

                    b.Property<string>("NormalizedName");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Homan.DAL.Entities.HomeSpace", b =>
                {
                    b.HasOne("Homan.DAL.Entities.User")
                        .WithMany("UserHomeSpaces")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Homan.DAL.Entities.HomeSpaceItem", b =>
                {
                    b.HasOne("Homan.DAL.Entities.HomeSpaceItemList", "HomeSpaceList")
                        .WithMany("HomeSpaceItems")
                        .HasForeignKey("HomeSpaceListId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Homan.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Homan.DAL.Entities.HomeSpaceItemList", b =>
                {
                    b.HasOne("Homan.DAL.Entities.HomeSpace", "HomeSpace")
                        .WithMany("HomeSpaceItems")
                        .HasForeignKey("HomeSpaceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Homan.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Homan.DAL.Entities.UserInHomeSpace", b =>
                {
                    b.HasOne("Homan.DAL.Entities.HomeSpace", "HomeSpace")
                        .WithMany("HomeSpaceUsers")
                        .HasForeignKey("HomeSpaceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Homan.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
